import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "web-services/specification/joomla-4-web-services-api-collection-for-postman",
    },
    {
      type: "category",
      label: "Banners",
      link: {
        type: "doc",
        id: "web-services/specification/banners",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/banners",
          label: "banners",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/banners",
          label: "banners",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-banner-id",
          label: "banners/{banner_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-banner-id",
          label: "banners/{banner_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-banner-id",
          label: "banners/{banner_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-clients",
          label: "banners/clients",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-clients",
          label: "banners/clients",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-clients-client-id",
          label: "banners/clients/{client_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-clients-client-id",
          label: "banners/clients/{client_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-clients-client-id",
          label: "banners/clients/{client_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-categories",
          label: "banners/categories",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-categories",
          label: "banners/categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-categories-category-id",
          label: "banners/categories/{category_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-categories-category-id",
          label: "banners/categories/{category_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-categories-category-id",
          label: "banners/categories/{category_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-contenthistory-keep-contenthistory-id",
          label: "banners/contenthistory/keep/{contenthistory_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-contenthistory-banner-id",
          label: "banners/contenthistory/{banner_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/banners-contenthistory-banner-id",
          label: "banners/contenthistory/{banner_id}",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Config",
      link: {
        type: "doc",
        id: "web-services/specification/config",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/config-application",
          label: "config/application",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/config-application",
          label: "config/application",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/config-component-name",
          label: "config/{component_name}",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Contacts",
      link: {
        type: "doc",
        id: "web-services/specification/contacts",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/contacts",
          label: "contacts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/contacts",
          label: "contacts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/contacts-contact-id",
          label: "contacts/{contact_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/contacts-contact-id",
          label: "contacts/{contact_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/contacts-contact-id",
          label: "contacts/{contact_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/contacts-form-contact-id",
          label: "contacts/form/{contact_id}",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-contacts-contact",
          label: "fields/contacts/contact",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-contacts-contact",
          label: "fields/contacts/contact",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-contacts-contact-field-id",
          label: "fields/contacts/contact/{field_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-contacts-contact-field-id",
          label: "fields/contacts/contact/{field_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-contacts-contact-field-id",
          label: "fields/contacts/contact/{field_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-contacts-contact",
          label: "fields/groups/contacts/contact",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-contacts-contact",
          label: "fields/groups/contacts/contact",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-contacts-contact-group-id",
          label: "fields/groups/contacts/contact/{group_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-contacts-contact-group-id",
          label: "fields/groups/contacts/contact/{group_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-contacts-contact-group-id",
          label: "fields/groups/contacts/contact/{group_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-contacts-categories",
          label: "fields/contacts/categories",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-contacts-categories",
          label: "fields/contacts/categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-contacts-categories-field-id",
          label: "fields/contacts/categories/{field_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-contacts-categories-field-id",
          label: "fields/contacts/categories/{field_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-contacts-categories-field-id",
          label: "fields/contacts/categories/{field_id}",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Content",
      link: {
        type: "doc",
        id: "web-services/specification/content",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/content-articles",
          label: "content/articles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/content-articles",
          label: "content/articles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/content-articles-article-id",
          label: "content/articles/{article_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/content-articles-article-id",
          label: "content/articles/{article_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/content-articles-article-id",
          label: "content/articles/{article_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-content-articles",
          label: "fields/content/articles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-content-articles",
          label: "fields/content/articles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-content-articles-field-id",
          label: "fields/content/articles/{field_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-content-articles-field-id",
          label: "fields/content/articles/{field_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-content-articles-field-id",
          label: "fields/content/articles/{field_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-content-articles",
          label: "fields/groups/content/articles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-content-articles",
          label: "fields/groups/content/articles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-content-articles-group-id",
          label: "fields/groups/content/articles/{group_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-content-articles-group-id",
          label: "fields/groups/content/articles/{group_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-content-articles-group-id",
          label: "fields/groups/content/articles/{group_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-content-categories",
          label: "fields/content/categories",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-content-categories",
          label: "fields/content/categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-content-categories-field-id",
          label: "fields/content/categories/{field_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-content-categories-field-id",
          label: "fields/content/categories/{field_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-content-categories-field-id",
          label: "fields/content/categories/{field_id}",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Languages",
      link: {
        type: "doc",
        id: "web-services/specification/languages",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/languages",
          label: "languages",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/languages",
          label: "languages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/languages-content",
          label: "languages/content",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/languages-content",
          label: "languages/content",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/languages-content-language-id",
          label: "languages/content/{language_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/languages-content-language-id",
          label: "languages/content/{language_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/v-1-languages-content-language-id",
          label: "v1/languages/content/{language_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/languages-overrides-app-lang-code",
          label: "languages/overrides/{app}/{lang_code}",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/languages-overrides-app-lang-code",
          label: "languages/overrides/{app}/{lang_code}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/languages-overrides-app-lang-code-constant-id",
          label: "languages/overrides/{app}/{lang_code}/{constant_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/languages-overrides-app-lang-code-constant-id",
          label: "languages/overrides/{app}/{lang_code}/{constant_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/languages-overrides-app-lang-code-constant-id",
          label: "languages/overrides/{app}/{lang_code}/{constant_id}",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Menus",
      link: {
        type: "doc",
        id: "web-services/specification/menus",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/menus-app",
          label: "menus/{app}",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/menus-app",
          label: "menus/{app}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/menus-app-menu-id",
          label: "menus/{app}/{menu_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/menus-app-menu-id",
          label: "menus/{app}/{menu_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/menus-app-menu-id",
          label: "menus/{app}/{menu_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/menus-app-items",
          label: "menus/{app}/items",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/menus-app-items",
          label: "menus/{app}/items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/menus-app-items-menu-item-id",
          label: "menus/{app}/items/{menu_item_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/menus-app-items-menu-item-id",
          label: "menus/{app}/items/{menu_item_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/menus-app-items-menu-item-id",
          label: "menus/{app}/items/{menu_item_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/menus-app-items-types",
          label: "menus/{app}/items/types",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Messages",
      link: {
        type: "doc",
        id: "web-services/specification/messages",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/messages",
          label: "messages",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/messages",
          label: "messages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/messages-message-id",
          label: "messages/{message_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/messages-message-id",
          label: "messages/{message_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/messages-message-id",
          label: "messages/{message_id}",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Modules",
      link: {
        type: "doc",
        id: "web-services/specification/modules",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/modules-app",
          label: "modules/{app}",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/modules-app",
          label: "modules/{app}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/modules-app-module-id",
          label: "modules/{app}/{module_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/modules-app-module-id",
          label: "modules/{app}/{module_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/modules-app-module-id",
          label: "modules/{app}/{module_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/modules-types-app",
          label: "modules/types/{app}",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Newsfeeds",
      link: {
        type: "doc",
        id: "web-services/specification/newsfeeds",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/newsfeeds-feeds",
          label: "newsfeeds/feeds",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/newsfeeds-feeds",
          label: "newsfeeds/feeds",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/newsfeeds-feeds-feed-id",
          label: "newsfeeds/feeds/{feed_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/newsfeeds-feeds-feed-id",
          label: "newsfeeds/feeds/{feed_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/newsfeeds-feeds-feed-id",
          label: "newsfeeds/feeds/{feed_id}",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Privacy",
      link: {
        type: "doc",
        id: "web-services/specification/privacy",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/privacy-requests",
          label: "privacy/requests",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/privacy-requests",
          label: "privacy/requests",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/privacy-requests-request-id",
          label: "privacy/requests/{request_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/privacy-requests-export-request-id",
          label: "privacy/requests/export/{request_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/privacy-consents",
          label: "privacy/consents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/privacy-consents-consent-id",
          label: "privacy/consents/{consent_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/privacy-consents-consent-id",
          label: "privacy/consents/{consent_id}",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Redirects",
      link: {
        type: "doc",
        id: "web-services/specification/redirects",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/redirect",
          label: "redirect",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/redirects-redirect-id",
          label: "redirects/{redirect_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/redirects-redirect-id",
          label: "redirects/{redirect_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/redirects-redirect-id",
          label: "redirects/{redirect_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/redirects",
          label: "redirects",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Tags",
      link: {
        type: "doc",
        id: "web-services/specification/tags",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/tags",
          label: "tags",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/tags",
          label: "tags",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/tags-tag-id",
          label: "tags/{tag_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/tags-tag-id",
          label: "tags/{tag_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/tags-tag-id",
          label: "tags/{tag_id}",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Templates",
      link: {
        type: "doc",
        id: "web-services/specification/templates",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/templates-styles-app",
          label: "templates/styles/{app}",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/templates-styles-app",
          label: "templates/styles/{app}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/templates-styles-app-template-style-id",
          label: "templates/styles/{app}/{template_style_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/templates-styles-app-template-style-id",
          label: "templates/styles/{app}/{template_style_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/templates-styles-app-template-style-id",
          label: "templates/styles/{app}/{template_style_id}",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      link: {
        type: "doc",
        id: "web-services/specification/users",
      },
      items: [
        {
          type: "doc",
          id: "web-services/specification/users",
          label: "users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/users",
          label: "users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/users-user-id",
          label: "users/{user_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/users-user-id",
          label: "users/{user_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/users-user-id",
          label: "users/{user_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-users",
          label: "fields/users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-users",
          label: "fields/users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-users-field-id",
          label: "fields/users/{field_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-users-field-id",
          label: "fields/users/{field_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-users-field-id",
          label: "fields/users/{field_id}",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-users",
          label: "fields/groups/users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-users",
          label: "fields/groups/users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-users-group-id",
          label: "fields/groups/users/{group_id}",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-users-group-id",
          label: "fields/groups/users/{group_id}",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "web-services/specification/fields-groups-users-group-id",
          label: "fields/groups/users/{group_id}",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Languages Search",
      items: [
        {
          type: "doc",
          id: "web-services/specification/languages-overrides-search",
          label: "languages/overrides/search",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "web-services/specification/languages-overrides-search-cache-refresh",
          label: "languages/overrides/search/cache/refresh",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
