---
kind: pipeline
name: default

clone:

steps:
  - name: build
    image: node:20-bookworm-slim
    commands:
      - npm install
      - npm run build

  - name: deployment
    image: joomlaprojects/docker-images:packager
    depends_on:
      - build
    environment:
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: CLOUDFLARE_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_API_TOKEN
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - echo "Prepare Workaround for trailing slashes bug https://github.com/facebook/docusaurus/issues/6282 on Cloudflare Pages"
      - >
        for f in build/assets/files/*; do
          [ -f "$f" ] || continue;
          filename=$(basename "$f");
          echo "/assets/files/$filename/ /assets/files/$filename 301";
        done > build/_redirects
      - node_modules/.bin/wrangler pages deploy ./build --commit-dirty=true --project-name manual --branch="$${DRONE_SOURCE_BRANCH}" | tee /tmp/output.log
      - export PREVIEW_UNIQUE_URL=`grep Deployment /tmp/output.log | awk '{ print $9 }'`
      - export PREVIEW_URL=`grep "Deployment alias URL" /tmp/output.log | awk '{ print $5 }'`
      - chmod +x test.sh
      - if [ ! -z "$${DRONE_PULL_REQUEST}" ]; then /bin/add_github_status.sh "Preview" "Generated preview for this pull request" "$${PREVIEW_URL}" ; fi;
    when:
      branch:
        main
      status:
        - success
      event:
        - push
        - pull_request

---
kind: signature
hmac: fd23674d231f74d54696c996b77acceb14a19d2d5d800c7050bdaee2f9be5b4b

...
